# Generated by Django 3.1.5 on 2021-02-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('Markdown', models.FileField(upload_to='blogposts')),
                ('related_posts', models.URLField()),
                ('ups', models.IntegerField(verbose_name='claps')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region', models.CharField(choices=[('HO', 'Hokkaido'), ('TO', 'Tohoku'), ('KT', 'Kanto'), ('CU', 'Chubu'), ('KS', 'Kansai'), ('CG', 'Chugoku'), ('SK', 'Shiokoku'), ('KY', 'Kyushu')], default='KT', max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('choice', models.CharField(choices=[('GEN', 'General'), ('ENT', 'Entertainment'), ('FOD', 'Food'), ('SPT', 'Sports'), ('BUS', 'Business'), ('LGL', 'Legal'), ('TIP', 'Tips')], default='GEN', max_length=3, primary_key=True, serialize=False)),
            ],
        ),
    ]
