# Generated by Django 3.1.6 on 2021-02-21 18:08

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('briefing', models.CharField(max_length=512)),
                ('content', tinymce.models.HTMLField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('featured', models.BooleanField(default=False)),
                ('related_posts', models.URLField(blank=True, null=True)),
                ('ups', models.IntegerField(default=0, verbose_name='claps')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region', models.CharField(choices=[('HO', 'Hokkaido'), ('TO', 'Tohoku'), ('KT', 'Kanto'), ('CU', 'Chubu'), ('KS', 'Kansai'), ('CG', 'Chugoku'), ('SK', 'Shiokoku'), ('KY', 'Kyushu')], default='KT', max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('choice', models.CharField(choices=[('GEN', 'General'), ('ENT', 'Entertainment'), ('FOD', 'Food'), ('SPT', 'Sports'), ('BUS', 'Business'), ('LGL', 'Legal'), ('TIP', 'Tips')], default='GEN', max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2048)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost')),
            ],
        ),
    ]
