# Generated by Django 3.1.6 on 2021-02-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210221_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='related_posts',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='_blogpost_related_posts_+', to='blog.Blogpost'),
        ),
    ]
