# Generated by Django 3.1.5 on 2021-02-19 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210219_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='time_created',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
