# Generated by Django 3.1.7 on 2021-02-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='Markdown',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
