# Generated by Django 3.1.6 on 2021-02-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210222_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='must_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='_blogpost_related_posts_+', to='blog.Blogpost'),
        ),
    ]
