# Generated by Django 3.1.5 on 2021-02-20 00:40

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210220_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
