# Generated by Django 3.1.5 on 2021-02-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210220_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='related_posts',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='ups',
            field=models.IntegerField(default=0, verbose_name='claps'),
        ),
    ]
