# Generated by Django 3.1.6 on 2021-02-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='briefing',
            field=models.CharField(default=' ', max_length=512),
            preserve_default=False,
        ),
    ]
